//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fotbollstips
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FotbollsTipsModel : DbContext
    {
        public FotbollsTipsModel()
            : base("name=FotbollsTipsModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TipsComment> TipsComments { get; set; }
        public virtual DbSet<TipsPathToPDF> TipsPathToPDFs { get; set; }
        public virtual DbSet<TipsRandomValue> TipsRandomValues { get; set; }
        public virtual DbSet<TipsData> TipsDatas { get; set; }
    }
}
