//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fotbollstips
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipsData
    {
        public int Id { get; set; }
        public string Namn { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public Nullable<bool> HasPayed { get; set; }
        public Nullable<int> Poäng { get; set; }
        public string Finallag1 { get; set; }
        public string Finallag2 { get; set; }
        public string Vinnare { get; set; }
        public string Frankrike_Sydkorea { get; set; }
        public string Tyskland_Kina { get; set; }
        public string Spanien_Sydafrika { get; set; }
        public string Norge_Nigeria { get; set; }
        public string Australien_Italien { get; set; }
        public string Brasilien_Jamaica { get; set; }
        public string England_Skottland { get; set; }
        public string Argentina_Japan { get; set; }
        public string Kanada_Kamerun { get; set; }
        public string NyaZeeland_Nederländerna { get; set; }
        public string Chile_Sverige { get; set; }
        public string Usa_Thailand { get; set; }
        public string Nigeria_Sydkorea { get; set; }
        public string Tyskland_Spanien { get; set; }
        public string Frankrike_Norge { get; set; }
        public string Australien_Brasilien { get; set; }
        public string Sydafrika_Kina { get; set; }
        public string Japan_Skottland { get; set; }
        public string Jamaica_Italien { get; set; }
        public string England_Argentina { get; set; }
        public string Nederländerna_Kamerun { get; set; }
        public string Kanada_NyaZeeland { get; set; }
        public string Sverige_Thailand { get; set; }
        public string Usa_Chile { get; set; }
        public string Kina_Spanien { get; set; }
        public string Sydafrika_Tyskland { get; set; }
        public string Nigeria_Frankrike { get; set; }
        public string Sydkorea_Norge { get; set; }
        public string Italien_Brasilien { get; set; }
        public string Jamaica_Australien { get; set; }
        public string Japan_England { get; set; }
        public string Skottland_Argentina { get; set; }
        public string Nederländerna_Kanada { get; set; }
        public string Kamerun_NyaZeeland { get; set; }
        public string Sverige_Usa { get; set; }
        public string Thailand_Chile { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
