//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fotbollstips
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipsPathToPDF
    {
        public int Id { get; set; }
        public Nullable<int> TipsData_SoftFK { get; set; }
        public string PathToPDF { get; set; }
    }
}
