//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fotbollstips
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipsData
    {
        public int Id { get; set; }
        public string Namn { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public Nullable<bool> HasPayed { get; set; }
        public Nullable<int> Poäng { get; set; }
        public string Finallag1 { get; set; }
        public string Finallag2 { get; set; }
        public string Vinnare { get; set; }
        public string Turkiet_Italien { get; set; }
        public string Wales_Schweiz { get; set; }
        public string Danmark_Finland { get; set; }
        public string Belgien_Ryssland { get; set; }
        public string England_Kroatien { get; set; }
        public string Österrike_Nordmakedonien { get; set; }
        public string Nederländerna_Ukraina { get; set; }
        public string Skottland_Tjeckien { get; set; }
        public string Polen_Slovakien { get; set; }
        public string Spanien_Sverige { get; set; }
        public string Ungern_Portugal { get; set; }
        public string Frankrike_Tyskland { get; set; }
        public string Finland_Ryssland { get; set; }
        public string Turkiet_Wales { get; set; }
        public string Italien_Schweiz { get; set; }
        public string Ukraina_Nordmakedonien { get; set; }
        public string Danmark_Belgien { get; set; }
        public string Nederländerna_Österrike { get; set; }
        public string Sverige_Slovakien { get; set; }
        public string Kroatien_Tjeckien { get; set; }
        public string England_Skottland { get; set; }
        public string Ungern_Frankrike { get; set; }
        public string Portugal_Tyskland { get; set; }
        public string Spanien_Polen { get; set; }
        public string Italien_Wales { get; set; }
        public string Schweiz_Turkiet { get; set; }
        public string Nordmakedonien_Nederländerna { get; set; }
        public string Ukraina_Österrike { get; set; }
        public string Ryssland_Danmark { get; set; }
        public string Finland_Belgien { get; set; }
        public string Tjeckien_England { get; set; }
        public string Kroatien_Skottland { get; set; }
        public string Slovakien_Spaninen { get; set; }
        public string Sverige_Polen { get; set; }
        public string Tyskland_Ungern { get; set; }
        public string Portugal_Frankrike { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
